#!/bin/sh
PIDFILE="/var/run/ntpd.pid"
NTPD_OPTS="-p 10.1.0.1"

has_ip()
{
  ifconfig wlan0 | grep -c inet
}

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" 2>/dev/null && echo "PID: $pid" || return 1
  fi
}

start() 
{
  echo "Starting ntpd..."
  echo "UTC" > /etc/TZ

  while [ $(has_ip) -eq 0 ]; do
    echo "No IP yet, waiting..."
    sleep 3
  done
  ntpd $NTPD_OPTS
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid || rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
