#!/bin/sh
PIDFILE="/var/run/rtsp-server.pid"

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  USE_NEW_VER=true

  if [ "$USE_NEW_VER" = true ] ; then
    echo "Will use new binary for RTSP server (github.com/davidjb)"
    RTSP_BIN="LD_LIBRARY_PATH=/media/mmcblk0p2/data/updates/snx_rtsp_server/lib /media/mmcblk0p2/data/updates/snx_rtsp_server/bin/snx_rtsp_server"
  else
    echo "Will use old binary for RTSP server (github.com/samtap)"
    RTSP_BIN="snx_rtsp_server"  
  fi
  LOG=/dev/null
  echo "Starting RTSP server..."
  auth=$(cat /media/mmcblk0p2/data/etc/rtsp.passwd)
  if [ "$auth" ]; then
    echo "... with auth"
    $RTSP_BIN -A "$auth" -g 24 -F 12 -i 24 -W 1280 -H 720 -b 512 -a >$LOG 2>&1 &
  else
    echo "... without auth"
    $RTSP_BIN -g 24 -F 12 -i 24 -W 1280 -H 720 -b 512 -a >$LOG 2>&1 &
  fi
  echo "$!" > "$PIDFILE"
  # Enable OSD with date time
  snx_isp_ctl --osdset-en 1 --osdset-ts 1 --osdset-template 1234567890./-:Date --osdset-gain 1 --osdset-bgtransp 0x1 --osdset-bgcolor 0x000000
  # No image rotation
  snx_isp_ctl --mfset-mode 0  
  # No Motion Detection
  snx_isp_ctl --mdset-en 0
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid ||  rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi

